#!/usr/bin/env python3
"""
Скрипт для создания маппинга брендов АвтоКонтинента к формату АвтоСпутника
"""

import os
import sys
import django
import json
from collections import defaultdict

# Настройка Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'shopapex_project.settings')
django.setup()

from catalog.models import AutoKontinentProduct

def normalize_brand(brand):
    """Нормализация бренда для сравнения"""
    if not brand:
        return ""
    return brand.lower().replace(' ', '').replace('-', '').replace('/', '').replace('\\', '')

def create_brand_mapping():
    """Создание маппинга брендов"""
    
    print("Анализируем бренды АвтоКонтинента...")
    
    # Получаем все уникальные бренды
    brands = AutoKontinentProduct.objects.values_list('brand', flat=True).distinct()
    brand_list = list(brands)
    
    print(f"Найдено {len(brand_list)} уникальных брендов")
    
    # Создаем маппинг
    brand_mapping = {}
    
    # Известные маппинги для АвтоСпутника
    known_mappings = {
        'mann': 'MANN-FILTER',
        'mahle': 'Knecht/Mahle',
        'knecht': 'Knecht/Mahle',
        'knechtmahle': 'Knecht/Mahle',
        'bosch': 'BOSCH',
        'febi': 'FEBI BILSTEIN',
        'bilstein': 'FEBI BILSTEIN',
        'febibilstein': 'FEBI BILSTEIN',
        'sachs': 'SACHS',
        'valeo': 'VALEO',
        'continental': 'CONTINENTAL',
        'delphi': 'DELPHI',
        'denso': 'DENSO',
        'ngk': 'NGK',
        'champion': 'CHAMPION',
        'fram': 'FRAM',
        'wix': 'WIX',
        'mobil': 'MOBIL',
        'castrol': 'CASTROL',
        'shell': 'SHELL',
        'total': 'TOTAL',
        'elf': 'ELF',
        'liqui moly': 'LIQUI MOLY',
        'liquimoly': 'LIQUI MOLY',
        'motul': 'MOTUL',
        'ravenol': 'RAVENOL',
        'zic': 'ZIC',
        'gulf': 'GULF',
        'texaco': 'TEXACO',
        'chevron': 'CHEVRON',
        'bp': 'BP',
        'esso': 'ESSO',
        'exxon': 'EXXON',
        'agip': 'AGIP',
        'eni': 'ENI',
        'repsol': 'REPSOL',
        'petronas': 'PETRONAS',
        'idemitsu': 'IDEMITSU',
        'cosmo': 'COSMO',
        'nippon': 'NIPPON',
        'kyb': 'KYB',
        'kayaba': 'KYB',
        'bilstein': 'BILSTEIN',
        'monroe': 'MONROE',
        'gabriel': 'GABRIEL',
        'rancho': 'RANCHO',
        'pro comp': 'PRO COMP',
        'procomp': 'PRO COMP',
        'skyjacker': 'SKYJACKER',
        'rough country': 'ROUGH COUNTRY',
        'roughcountry': 'ROUGH COUNTRY',
        'zone': 'ZONE',
        'bds': 'BDS',
        'fabtech': 'FABTECH',
        'cst': 'CST',
        'cooper': 'COOPER',
        'bfgoodrich': 'BFGOODRICH',
        'bf goodrich': 'BFGOODRICH',
        'goodyear': 'GOODYEAR',
        'michelin': 'MICHELIN',
        'bridgestone': 'BRIDGESTONE',
        'firestone': 'FIRESTONE',
        'dunlop': 'DUNLOP',
        'pirelli': 'PIRELLI',
        'hankook': 'HANKOOK',
        'kumho': 'KUMHO',
        'toyo': 'TOYO',
        'yokohama': 'YOKOHAMA',
        'falken': 'FALKEN',
        'nitto': 'NITTO',
        'maxxis': 'MAXXIS',
        'kenda': 'KENDA',
        'triangle': 'TRIANGLE',
        'linglong': 'LINGLONG',
        'doublestar': 'DOUBLESTAR',
        'double star': 'DOUBLESTAR',
        'giti': 'GITI',
        'roadstone': 'ROADSTONE',
        'nexen': 'NEXEN',
        'nankang': 'NANKANG',
        'federal': 'FEDERAL',
        'achilles': 'ACHILLES',
        'gt radial': 'GT RADIAL',
        'gtradial': 'GT RADIAL',
        'apollo': 'APOLLO',
        'ceat': 'CEAT',
        'mr': 'MR',
        'mr.': 'MR',
        'mr. gasket': 'MR. GASKET',
        'mrgasket': 'MR. GASKET',
        'fel-pro': 'FEL-PRO',
        'felpro': 'FEL-PRO',
        'victor reinz': 'VICTOR REINZ',
        'victorreinz': 'VICTOR REINZ',
        'corteco': 'CORTECO',
        'elring': 'ELRING',
        'goetze': 'GOETZE',
        'payen': 'PAYEN',
        'atp': 'ATP',
        'beck arnley': 'BECK ARNLEY',
        'beckarnley': 'BECK ARNLEY',
        'gates': 'GATES',
        'dayco': 'DAYCO',
        'continental': 'CONTINENTAL',
        'goodyear': 'GOODYEAR',
        'bando': 'BANDO',
        'mitsuboshi': 'MITSUBOSHI',
        'optibelt': 'OPTIBELT',
        'habasit': 'HABASIT',
        'skf': 'SKF',
        'fag': 'FAG',
        'ina': 'INA',
        'nsk': 'NSK',
        'ntn': 'NTN',
        'koyo': 'KOYO',
        'timken': 'TIMKEN',
        'federal mogul': 'FEDERAL MOGUL',
        'federalmogul': 'FEDERAL MOGUL',
        'mahle clevite': 'MAHLE CLEVITE',
        'mahleclevite': 'MAHLE CLEVITE',
        'king': 'KING',
        'acl': 'ACL',
        'clevite': 'CLEVITE',
        'durabond': 'DURABOND',
        'glacier': 'GLACIER',
        'vandervell': 'VANDERVELL',
        'glyco': 'GLYCO',
        'npr': 'NPR',
        'nippon piston ring': 'NPR',
        'nipponpistonring': 'NPR',
        'art': 'ART',
        'art pistons': 'ART',
        'artpistons': 'ART',
        'je': 'JE',
        'je pistons': 'JE',
        'jepistons': 'JE',
        'wiseco': 'WISECO',
        'cp': 'CP',
        'cp pistons': 'CP',
        'cppistons': 'CP',
        'arias': 'ARIAS',
        'arias pistons': 'ARIAS',
        'ariaspistons': 'ARIAS',
        'ross': 'ROSS',
        'ross pistons': 'ROSS',
        'rosspistons': 'ROSS',
        'mahle': 'MAHLE',
        'mahle pistons': 'MAHLE',
        'mahlepistons': 'MAHLE',
        'omega': 'OMEGA',
        'omega pistons': 'OMEGA',
        'omegapistons': 'OMEGA',
        'silvolite': 'SILVOLITE',
        'silvolite pistons': 'SILVOLITE',
        'silvolitepistons': 'SILVOLITE',
        'sealed power': 'SEALED POWER',
        'sealedpower': 'SEALED POWER',
        'speed pro': 'SPEED PRO',
        'speedpro': 'SPEED PRO',
        'trw': 'TRW',
        'trw automotive': 'TRW',
        'trwautomotive': 'TRW',
        'lucas': 'LUCAS',
        'lucas electrical': 'LUCAS',
        'lucaselectrical': 'LUCAS',
        'hella': 'HELLA',
        'osram': 'OSRAM',
        'philips': 'PHILIPS',
        'sylvania': 'SYLVANIA',
        'ge': 'GE',
        'general electric': 'GE',
        'generalelectric': 'GE',
        'westinghouse': 'WESTINGHOUSE',
        'eiko': 'EIKO',
        'wagner': 'WAGNER',
        'tungsram': 'TUNGSRAM',
        'narva': 'NARVA',
        'autolite': 'AUTOLITE',
        'champion': 'CHAMPION',
        'ngk': 'NGK',
        'denso': 'DENSO',
        'beru': 'BERU',
        'bosch': 'BOSCH',
        'ac delco': 'AC DELCO',
        'acdelco': 'AC DELCO',
        'delco': 'AC DELCO',
        'motorcraft': 'MOTORCRAFT',
        'ford': 'FORD',
        'chevrolet': 'CHEVROLET',
        'chevrolet performance': 'CHEVROLET PERFORMANCE',
        'chevroletperformance': 'CHEVROLET PERFORMANCE',
        'gm': 'GM',
        'general motors': 'GM',
        'generalmotors': 'GM',
        'chrysler': 'CHRYSLER',
        'dodge': 'DODGE',
        'jeep': 'JEEP',
        'ram': 'RAM',
        'fiat': 'FIAT',
        'alfa romeo': 'ALFA ROMEO',
        'alfaromeo': 'ALFA ROMEO',
        'lancia': 'LANCIA',
        'maserati': 'MASERATI',
        'ferrari': 'FERRARI',
        'lamborghini': 'LAMBORGHINI',
        'porsche': 'PORSCHE',
        'volkswagen': 'VOLKSWAGEN',
        'vw': 'VOLKSWAGEN',
        'audi': 'AUDI',
        'bmw': 'BMW',
        'mercedes': 'MERCEDES',
        'mercedes-benz': 'MERCEDES',
        'mercedesbenz': 'MERCEDES',
        'opel': 'OPEL',
        'vauxhall': 'VAUXHALL',
        'saab': 'SAAB',
        'volvo': 'VOLVO',
        'scania': 'SCANIA',
        'man': 'MAN',
        'iveco': 'IVECO',
        'renault': 'RENAULT',
        'peugeot': 'PEUGEOT',
        'citroen': 'CITROEN',
        'ds': 'DS',
        'toyota': 'TOYOTA',
        'lexus': 'LEXUS',
        'honda': 'HONDA',
        'acura': 'ACURA',
        'nissan': 'NISSAN',
        'infiniti': 'INFINITI',
        'mazda': 'MAZDA',
        'subaru': 'SUBARU',
        'mitsubishi': 'MITSUBISHI',
        'suzuki': 'SUZUKI',
        'daihatsu': 'DAIHATSU',
        'isuzu': 'ISUZU',
        'hyundai': 'HYUNDAI',
        'kia': 'KIA',
        'ssangyong': 'SSANGYONG',
        'daewoo': 'DAEWOO',
        'skoda': 'SKODA',
        'seat': 'SEAT',
        'jaguar': 'JAGUAR',
        'land rover': 'LAND ROVER',
        'landrover': 'LAND ROVER',
        'range rover': 'RANGE ROVER',
        'rangerover': 'RANGE ROVER',
        'mini': 'MINI',
        'rover': 'ROVER',
        'mg': 'MG',
        'aston martin': 'ASTON MARTIN',
        'astonmartin': 'ASTON MARTIN',
        'bentley': 'BENTLEY',
        'rolls royce': 'ROLLS ROYCE',
        'rollsroyce': 'ROLLS ROYCE',
        'lotus': 'LOTUS',
        'mclaren': 'MCLAREN',
        'caterham': 'CATERHAM',
        'noble': 'NOBLE',
        'ariel': 'ARIEL',
        'radical': 'RADICAL',
        'ginetta': 'GINETTA',
        'westfield': 'WESTFIELD',
        'caterham': 'CATERHAM',
        'donkervoort': 'DONKERVOORT',
        'spyker': 'SPYKER',
        'pagani': 'PAGANI',
        'bugatti': 'BUGATTI',
        'koenigsegg': 'KOENIGSEGG',
        'rimac': 'RIMAC',
        'pininfarina': 'PININFARINA',
        'bertone': 'BERTONE',
        'italdesign': 'ITALDESIGN',
        'ghia': 'GHIA',
        'zagato': 'ZAGATO',
        'tourist': 'TOURIST',
        'touring': 'TOURING',
        'vignale': 'VIGNALE',
        'ghia': 'GHIA',
        'osca': 'OSCA',
        'abarth': 'ABARTH',
        'lancia': 'LANCIA',
        'alfa romeo': 'ALFA ROMEO',
        'alfaromeo': 'ALFA ROMEO',
        'fiat': 'FIAT',
        'maserati': 'MASERATI',
        'ferrari': 'FERRARI',
        'lamborghini': 'LAMBORGHINI',
        'pagani': 'PAGANI',
        'bugatti': 'BUGATTI',
        'koenigsegg': 'KOENIGSEGG',
        'rimac': 'RIMAC',
        'pininfarina': 'PININFARINA',
        'bertone': 'BERTONE',
        'italdesign': 'ITALDESIGN',
        'ghia': 'GHIA',
        'zagato': 'ZAGATO',
        'tourist': 'TOURIST',
        'touring': 'TOURING',
        'vignale': 'VIGNALE',
        'ghia': 'GHIA',
        'osca': 'OSCA',
        'abarth': 'ABARTH',
        'lancia': 'LANCIA',
        'alfa romeo': 'ALFA ROMEO',
        'alfaromeo': 'ALFA ROMEO',
        'fiat': 'FIAT',
        'maserati': 'MASERATI',
        'ferrari': 'FERRARI',
        'lamborghini': 'LAMBORGHINI',
        'pagani': 'PAGANI',
        'bugatti': 'BUGATTI',
        'koenigsegg': 'KOENIGSEGG',
        'rimac': 'RIMAC',
        'pininfarina': 'PININFARINA',
        'bertone': 'BERTONE',
        'italdesign': 'ITALDESIGN',
        'ghia': 'GHIA',
        'zagato': 'ZAGATO',
        'tourist': 'TOURIST',
        'touring': 'TOURING',
        'vignale': 'VIGNALE',
        'ghia': 'GHIA',
        'osca': 'OSCA',
        'abarth': 'ABARTH',
    }
    
    # Применяем известные маппинги
    for brand in brand_list:
        if brand:
            normalized = normalize_brand(brand)
            if normalized in known_mappings:
                brand_mapping[brand] = known_mappings[normalized]
            else:
                # Если нет известного маппинга, оставляем как есть
                brand_mapping[brand] = brand
    
    # Сохраняем маппинг в файл
    with open('brand_analysis_results.json', 'w', encoding='utf-8') as f:
        json.dump(brand_mapping, f, ensure_ascii=False, indent=2)
    
    print(f"Создан маппинг для {len(brand_mapping)} брендов")
    print("Файл brand_analysis_results.json сохранен")
    
    # Показываем примеры маппинга
    print("\nПримеры маппинга:")
    for i, (old_brand, new_brand) in enumerate(list(brand_mapping.items())[:10]):
        print(f"{old_brand} -> {new_brand}")
    
    return brand_mapping

if __name__ == "__main__":
    create_brand_mapping() 