# Generated by Django 5.2.4 on 2025-07-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название баннера')),
                ('banner_type', models.CharField(choices=[('main', 'Главный баннер'), ('sidebar', 'Боковой баннер'), ('footer', 'Баннер в футере'), ('category', 'Баннер категории')], max_length=20, verbose_name='Тип баннера')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('text', models.TextField(blank=True, verbose_name='Текст баннера')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала показа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания показа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('external_link', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Блок главной страницы',
                'verbose_name_plural': 'Блоки главной страницы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HTMLBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блока')),
                ('position', models.CharField(choices=[('header', 'Шапка сайта'), ('sidebar', 'Боковая панель'), ('footer', 'Футер'), ('home_top', 'Главная - верх'), ('home_bottom', 'Главная - низ'), ('catalog_top', 'Каталог - верх'), ('product_bottom', 'Страница товара - низ')], max_length=20, verbose_name='Позиция')),
                ('html_content', models.TextField(verbose_name='HTML содержимое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'HTML блок',
                'verbose_name_plural': 'HTML блоки',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название слайдера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('autoplay', models.BooleanField(default=True, verbose_name='Автопрокрутка')),
                ('autoplay_speed', models.PositiveIntegerField(default=5000, verbose_name='Скорость автопрокрутки (мс)')),
                ('loop', models.BooleanField(default=True, verbose_name='Зацикливание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='Название магазина')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Слоган')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta keywords')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('footer_copyright', models.TextField(blank=True, verbose_name='Копирайт в футере')),
                ('vk_group', models.URLField(blank=True, verbose_name='Группа ВКонтакте')),
                ('telegram_group', models.URLField(blank=True, verbose_name='Группа Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
        migrations.CreateModel(
            name='CatalogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('show_products', models.BooleanField(default=True, verbose_name='Показывать товары')),
                ('products_count', models.PositiveIntegerField(default=8, verbose_name='Количество товаров')),
                ('sort_by', models.CharField(default='created_at', max_length=20, verbose_name='Сортировка товаров')),
                ('categories', models.ManyToManyField(blank=True, to='catalog.productcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Блок каталога',
                'verbose_name_plural': 'Блоки каталогов',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL слаг')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок слайда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Текст ссылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.slider', verbose_name='Слайдер')),
            ],
            options={
                'verbose_name': 'Элемент слайдера',
                'verbose_name_plural': 'Элементы слайдера',
                'ordering': ['order'],
            },
        ),
    ]
