# Generated by Django 5.2.4 on 2025-07-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlblock',
            name='position',
            field=models.CharField(choices=[('header', 'Шапка сайта'), ('sidebar', 'Боковая панель'), ('footer', 'Футер'), ('home_top', 'Главная - верх'), ('home_bottom', 'Главная - низ'), ('catalog_top', 'Каталог - верх'), ('product_bottom', 'Страница товара - низ'), ('contacts', 'Страница контактов')], max_length=20, verbose_name='Позиция'),
        ),
    ]
