# Маппинг брендов для нормализации
# Формат: 'Бренд из Mikado': 'Бренд в AutoSputnik'

BRAND_MAPPING = {
    'ZIMMERMANN': 'Otto Zimmermann',
    'VICTOR REINZ': 'REINZ',
    'MANN': 'MANN-FILTER',
    'KNECHT': 'Knecht/Mahle',
    'MAHLE ORIGINAL': 'Knecht/Mahle',
    'FEBI BILSTEIN': 'FEBI',
    'CITROËN': 'CITROEN/PEUGEOT',
    'PEUGEOT': 'CITROEN/PEUGEOT',
    'FIAT': 'Fiat/Alfa/Lancia',
    'KIA HYUNDAI': 'HYUNDAI/KIA',
    'HYUNDAI': 'HYUNDAI/KIA',
    'KIA': 'HYUNDAI/KIA',
    'ZF PARTS': 'ZF PARTS',
    'ZF Parts': 'ZF PARTS',
    'ZF RUSSIA': 'ZF PARTS',
    '1-56 MARUICHI': '1-56',
    'ACDelco': 'AC Delco',
    'AVA QUALITY COOLING': 'AVA',
    'BASBUG': 'BSG',
    'CHINASPARE': 'CHINA',
    'DELTA': 'DELTA AUTOTECHNIK',
    'DOCTORWAX': 'DOCTOR WAX',
    'DPGroup': 'DP GROUP',
    'HALLA': 'HCC',
    'HANON': 'HANON SYSTEMS',
    'JAPANPARTS': 'JAPAN PARTS',
    'KYB': 'KAYABA',
    'LEMFÖRDER': 'LEMFORDER',
    'LESJÖFORS': 'LESJOFORS',
    'MAGTECHNIC': 'MAG',
    'MALÒ': 'MALO',
    'MEAT & DORIA': 'MEAT DORIA',
    'MENSAN': 'ASP',
    'MERCEDES-BENZ': 'MERCEDES',
    'MK Kashiyama': 'KASHIYAMA',
    'NEVSKY FILTER': 'НЕВСКИЙ ФИЛЬТР',
    'PHC Valeo': 'VALEO PHC',
    'PRO PARTS SWEDEN AB': 'PROPARTS',
    'R&A': 'HWASEUNG R&A',
    'REACH Cooling': 'REACH',
    'Rheinol': 'SWD RHEINOL',
    'ROADHOUSE': 'ROAD HOUSE',
    'S.H': 'SH AUTO PARTS',
    'SANGSIN BRAKE': 'SANGSIN',
    'SCT Germany': 'SCT',
    'STARTVOLT': 'СТАРТВОЛЬТ',
    'Teikoku Piston Ring': 'TP',
    'VMP': 'VMPAUTO',
    'AllBalls': 'ALL BALLS RACING',
    'Auto Gur': 'AUTO-GUR',
    'Bendix': 'JURID/BENDIX',
    'BF Germany': 'BF',
    'CEI': 'C.E.I.',
    'Cobra': 'COBRA TUNING',
    'Continental': 'CONTITECH',
    'Delta': 'DELTA AVTO',
    'Detail': 'DETAIL LINE',
    'DPA': 'DIAMOND/DPA',
    'E&E Turbo': 'E&E',
    'Fomar': 'FOMAR FRICTION',
    'Gerat Original': 'GERAT',
    'GKN': 'LOEBRO',
    'Hiflo': 'HIFLO FILTRO',
    'Hyundai Xteer': 'HYUNDAI/KIA',
    'K-Flex': 'KAYABA',
    'King Bearings': 'KING',
    'Knorr': 'KNORR-BREMSE',
    'Lema': 'LE.MA.',
    'Lynx': 'LYNXAUTO',
    'Mahle': 'KNECHT/MAHLE',
    'Mahle kolben': 'KNECHT/MAHLE',
    'M Filter': 'MFILTER',
    'MK Kashiyama': 'KASHIYAMA',
    'OE Bentley': 'BENTLEY',
    'OE BMW': 'BMW',
    'OE BPW': 'BPW',
    'OE Brilliance': 'BRILLIANCE',
    'OE BYD': 'BYD',
    'OE Caterpillar': 'CATERPILLAR',
    'OE Changan': 'CHANGAN',
    'OE Chery': 'CHERY',
    'OE Chrysler/Dodge/Jeep': 'CHRYSLER',
    'OE Daewoo': 'DAEWOO',
    'OE DAF': 'DAF',
    'OE Dongfeng': 'DONGFENG',
    'OE Evolute': 'Evolute',
    'OE FAW': 'FAW',
    'OE Fiat/Alfa Romeo/Lancia': 'FIAT/ALFA/LANCIA',
    'OE Ford': 'Ford',
    'OE GAZ': 'GAZ',
    'OE Geely': 'Geely',
    'OE General Motors': 'General Motors',
    'OE-Germany': 'OEG',
    'OE Great Wall': 'Great Wall',
    'OE Haval': 'Haval',
    'OE Honda/Acura': 'HONDA',
    'OE Hyundai/Kia': 'HYUNDAI/KIA',
    'OE Isuzu': 'ISUZU',
    'OE Iveco': 'Iveco',
    'OE JAC Motors': 'JAC',
    'OE Jaguar': 'JAGUAR',
    'OE JMC': 'JMC',
    'OE JCB': 'JCB LANDPOWER',
    'OE Kaiyi': 'KAIYI',
    'OE Kamaz': 'KAMAZ',
    'OE Kawasaki': 'KAWASAKI',
    'OE Lada': 'LADA',
    'OE Land Rover': 'LAND ROVER',
    'OE Lifan': 'LIFAN',
    'OE Lombardini': 'LOMBARDINI',
    'OE MAN': 'MAZ',
    'OE Mazda': 'Mazda',
    'OE Mercedes Benz': 'Mercedes',
    'OE Mitsubishi': 'Mitsubishi',
    'OE Nissan/Infiniti': 'Nissan',
    'OE Omoda': 'OMODA',
    'OE PAZ': 'PAZ',
    'OE Porsche': 'PORSCHE',
    'OE SAF Holland': 'SAF',
    'OE PSA': 'CITROEN/PEUGEOT',
    'OE Renault': 'Renault',
    'OE Scania': 'SCANIA',
    'OE Schmitz ': 'SITRAK',
    'OE Shacman': 'SHACMAN',
    'OE Sitrak': 'SCANIA',
    'OE Ssang Yong': 'SSANGYONG',
    'OE Subaru': 'SUBARU',
    'OE Suzuki': 'SUZUKI',
    'OE Tesla': 'TESLA',
    'OE Toyota/Lexus': 'TOYOTA',
    'OE UAZ': 'UAZ',
    'OE Ural': 'URAL',
    'OE VAG': 'VAG',
    'OE Volvo': 'Volvo',
    'OE Yamaha': 'YAMAHA',
    'OJD Quick Brake': 'QUICK BRAKE',
    'Oris ': 'ORIS ELECTRONICS',
    'PAAZ': 'ПААЗ',
    'TGC': 'ТОСОЛ-СИНТЕЗ',
    'Tosol-Sintez ': 'ORIS ELECTRONICS',
    'TTT': 'TTT-AUTO',
    'ВМПАвто': 'VMPAUTO',
    'WAI': 'Global WAIGlobal WAI',
    'БелАК  Engine Components': 'БЕЛАВТОКОМПЛЕКТ'
}

def normalize_brand(brand_name: str) -> str:
    """
    Нормализует бренд к формату AutoSputnik
    """
    return BRAND_MAPPING.get(brand_name, brand_name)

def get_all_brand_variants() -> dict:
    """
    Возвращает все варианты брендов для поиска
    """
    return BRAND_MAPPING 