# Generated by Django 5.2.4 on 2025-07-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_pattern', models.CharField(max_length=17, verbose_name='VIN паттерн')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year_from', models.PositiveIntegerField(verbose_name='Год от')),
                ('year_to', models.PositiveIntegerField(verbose_name='Год до')),
                ('engine_type', models.CharField(blank=True, max_length=100, verbose_name='Тип двигателя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('products', models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Подходящие товары')),
            ],
            options={
                'verbose_name': 'Запись VIN базы',
                'verbose_name_plural': 'VIN база данных',
                'ordering': ['make', 'model', 'year_from'],
            },
        ),
        migrations.CreateModel(
            name='VinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='Номер запроса')),
                ('request_type', models.CharField(choices=[('vin', 'VIN код'), ('frame', 'FRAME номер')], max_length=10, verbose_name='Тип запроса')),
                ('vin_code', models.CharField(blank=True, max_length=17, verbose_name='VIN код')),
                ('frame_number', models.CharField(blank=True, max_length=20, verbose_name='FRAME номер')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон клиента')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email клиента')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Обработан'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_vin_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'VIN запрос',
                'verbose_name_plural': 'VIN запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('engine_type', models.CharField(blank=True, max_length=100, verbose_name='Тип двигателя')),
                ('engine_volume', models.CharField(blank=True, max_length=20, verbose_name='Объем двигателя')),
                ('transmission', models.CharField(blank=True, max_length=50, verbose_name='Коробка передач')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='Тип кузова')),
                ('drive_type', models.CharField(blank=True, max_length=20, verbose_name='Привод')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Страна происхождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('vin_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_info', to='vin_search.vinrequest', verbose_name='VIN запрос')),
            ],
            options={
                'verbose_name': 'Информация об автомобиле',
                'verbose_name_plural': 'Информация об автомобилях',
            },
        ),
        migrations.CreateModel(
            name='VinSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('compatibility_note', models.TextField(blank=True, verbose_name='Примечание о совместимости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
                ('vin_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='vin_search.vinrequest', verbose_name='VIN запрос')),
            ],
            options={
                'verbose_name': 'Результат поиска по VIN',
                'verbose_name_plural': 'Результаты поиска по VIN',
                'unique_together': {('vin_request', 'product')},
            },
        ),
    ]
