# Generated by Django 5.0 on 2025-07-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставщика')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('api_url', models.URLField(blank=True, verbose_name='URL API')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API ключ')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='API секрет')),
                ('data_format', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV')], default='json', max_length=10, verbose_name='Формат данных')),
                ('sync_frequency', models.CharField(choices=[('hourly', 'Каждый час'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('manual', 'Только вручную')], default='manual', max_length=20, verbose_name='Частота синхронизации')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Наценка (%)')),
                ('auto_activate_products', models.BooleanField(default=False, verbose_name='Автоматически активировать товары')),
                ('category_mapping', models.JSONField(blank=True, default=dict, verbose_name='Маппинг категорий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='primary_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='catalog.supplier', verbose_name='Основной поставщик'),
        ),
        migrations.CreateModel(
            name='SupplierSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено'), ('error', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('products_created', models.PositiveIntegerField(default=0, verbose_name='Товаров создано')),
                ('products_updated', models.PositiveIntegerField(default=0, verbose_name='Товаров обновлено')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Количество ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_article', models.CharField(max_length=100, verbose_name='Артикул поставщика')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена поставщика')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество у поставщика')),
                ('data', models.JSONField(default=dict, verbose_name='Данные от поставщика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='catalog.product', verbose_name='Товар в каталоге')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Товар поставщика',
                'verbose_name_plural': 'Товары поставщиков',
                'ordering': ['-updated_at'],
                'unique_together': {('supplier', 'supplier_article')},
            },
        ),
    ]
