# Generated by Django 5.2.4 on 2025-07-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_supplier_product_primary_supplier_suppliersynclog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='api_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин API'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='api_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль API'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='api_type',
            field=models.CharField(choices=[('custom', 'Пользовательский API'), ('autoparts', 'API автозапчастей')], default='custom', max_length=20, verbose_name='Тип API'),
        ),
        migrations.CreateModel(
            name='SupplierClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID в API')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_groups', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Группа клиентов поставщика',
                'verbose_name_plural': 'Группы клиентов поставщика',
                'ordering': ['name'],
                'unique_together': {('supplier', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='SupplierClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID в API')),
                ('name', models.CharField(max_length=200, verbose_name='Название/Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='catalog.supplier', verbose_name='Поставщик')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierclientgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Клиент поставщика',
                'verbose_name_plural': 'Клиенты поставщика',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID в API')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('days_min', models.PositiveIntegerField(default=1, verbose_name='Минимум дней')),
                ('days_max', models.PositiveIntegerField(default=7, verbose_name='Максимум дней')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_methods', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Способ доставки поставщика',
                'verbose_name_plural': 'Способы доставки поставщика',
                'ordering': ['name'],
                'unique_together': {('supplier', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID в API')),
                ('number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая сумма')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierclient', verbose_name='Клиент')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierdeliverymethod', verbose_name='Способ доставки')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Заказ поставщика',
                'verbose_name_plural': 'Заказы поставщика',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итого')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.supplierorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа поставщика',
                'verbose_name_plural': 'Позиции заказов поставщика',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID в API')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус')),
                ('notify_client', models.BooleanField(default=True, verbose_name='Уведомлять клиента')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Статус заказа поставщика',
                'verbose_name_plural': 'Статусы заказов поставщика',
                'ordering': ['name'],
                'unique_together': {('supplier', 'external_id')},
            },
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierorderstatus', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SupplierStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='ID в API')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Сотрудник поставщика',
                'verbose_name_plural': 'Сотрудники поставщика',
                'ordering': ['name'],
                'unique_together': {('supplier', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='catalog.supplierorder', verbose_name='Заказ')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierorderstatus', verbose_name='Статус')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierstaff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'История заказа поставщика',
                'verbose_name_plural': 'История заказов поставщика',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supplierclient',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierstaff', verbose_name='Менеджер'),
        ),
        migrations.CreateModel(
            name='SupplierBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Пополнение'), ('debit', 'Списание')], max_length=10, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='catalog.supplier', verbose_name='Поставщик')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='catalog.supplierclient', verbose_name='Клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierorder', verbose_name='Связанный заказ')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplierstaff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Транзакция баланса',
                'verbose_name_plural': 'Транзакции баланса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('supplier', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierclient',
            unique_together={('supplier', 'external_id')},
        ),
    ]
