# Generated by Django 5.2.4 on 2025-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_supplier_api_login_supplier_api_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='admin_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин API-администратора'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='admin_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль API-администратора'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин API (клиентский)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль API (клиентский)'),
        ),
    ]
