# Generated by Django 5.2.4 on 2025-07-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_admin_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='use_mock_admin_api',
            field=models.BooleanField(default=True, verbose_name='Использовать mock данные для админ API'),
        ),
    ]
