# Generated by Django 5.2.4 on 2025-07-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_mock_admin_api_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_shipment_address',
            field=models.CharField(default='0', help_text='0 = самовывоз, другие значения = ID адреса доставки', max_length=50, verbose_name='Адрес доставки по умолчанию'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='office_id',
            field=models.CharField(blank=True, help_text='Идентификатор офиса для методов API', max_length=50, verbose_name='ID офиса поставщика'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='use_online_stocks',
            field=models.BooleanField(default=False, help_text='Включает поиск по онлайн складам', verbose_name='Использовать онлайн склады'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='admin_login',
            field=models.CharField(blank=True, help_text='Логин для административных методов ABCP API (cp/*)', max_length=100, verbose_name='Логин API-администратора'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='admin_password',
            field=models.CharField(blank=True, help_text='Пароль для административных методов ABCP API', max_length=100, verbose_name='Пароль API-администратора'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='use_mock_admin_api',
            field=models.BooleanField(default=True, help_text='Если True, административные методы возвращают тестовые данные', verbose_name='Использовать mock данные для админ API'),
        ),
    ]
