# Generated by Django 5.2.4 on 2025-07-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_abcp_api_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_healthy', models.BooleanField(default=True, verbose_name='Работоспособен')),
                ('last_check_at', models.DateTimeField(auto_now=True, verbose_name='Последняя проверка')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('success_rate_24h', models.FloatField(default=100.0, verbose_name='Процент успешных запросов за 24ч')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='Среднее время ответа (сек)')),
                ('total_requests_today', models.IntegerField(default=0, verbose_name='Всего запросов сегодня')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Состояние API',
                'verbose_name_plural': 'Состояние API поставщиков',
            },
        ),
        migrations.CreateModel(
            name='APIMonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100, verbose_name='API метод')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('timeout', 'Таймаут'), ('auth_error', 'Ошибка авторизации')], max_length=20, verbose_name='Статус')),
                ('response_time', models.FloatField(verbose_name='Время ответа (сек)')),
                ('request_data', models.JSONField(default=dict, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(default=dict, verbose_name='Данные ответа')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Лог API запроса',
                'verbose_name_plural': 'Логи API запросов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier', 'created_at'], name='catalog_api_supplie_15cdbd_idx'), models.Index(fields=['status', 'created_at'], name='catalog_api_status_45e32b_idx')],
            },
        ),
    ]
