# Generated by Django 5.2.4 on 2025-07-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_api_monitoring'),
    ]

    operations = [
    ]
