# Generated by Django 5.2.4 on 2025-07-09 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20250709_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apihealthcheck',
            options={'ordering': ['-checked_at'], 'verbose_name': 'Проверка доступности API', 'verbose_name_plural': 'Проверки доступности API'},
        ),
        migrations.AlterModelOptions(
            name='apimonitorlog',
            options={'ordering': ['-checked_at'], 'verbose_name': 'Лог мониторинга API', 'verbose_name_plural': 'Логи мониторинга API'},
        ),
        migrations.AlterModelOptions(
            name='supplierbalancetransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция баланса поставщика', 'verbose_name_plural': 'Транзакции баланса поставщика'},
        ),
        migrations.AlterModelOptions(
            name='supplierorderhistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'История заказа поставщика', 'verbose_name_plural': 'История заказов поставщика'},
        ),
        migrations.AlterModelOptions(
            name='supplierorderitem',
            options={'verbose_name': 'Позиция заказа поставщика', 'verbose_name_plural': 'Позиции заказов поставщика'},
        ),
        migrations.AlterModelOptions(
            name='suppliersynclog',
            options={'ordering': ['-started_at'], 'verbose_name': 'Лог синхронизации поставщика', 'verbose_name_plural': 'Логи синхронизации поставщиков'},
        ),
        migrations.RemoveIndex(
            model_name='apimonitorlog',
            name='catalog_api_supplie_15cdbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='apimonitorlog',
            name='catalog_api_status_45e32b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='supplierclient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierclientgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierdeliverymethod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorderstatus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplierstaff',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='apihealthcheck',
            name='avg_response_time',
        ),
        migrations.RemoveField(
            model_name='apihealthcheck',
            name='is_healthy',
        ),
        migrations.RemoveField(
            model_name='apihealthcheck',
            name='last_check_at',
        ),
        migrations.RemoveField(
            model_name='apihealthcheck',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='apihealthcheck',
            name='success_rate_24h',
        ),
        migrations.RemoveField(
            model_name='apihealthcheck',
            name='total_requests_today',
        ),
        migrations.RemoveField(
            model_name='apimonitorlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierbalancetransaction',
            name='data',
        ),
        migrations.RemoveField(
            model_name='supplierbalancetransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplierorderhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierorderhistory',
            name='data',
        ),
        migrations.RemoveField(
            model_name='supplierorderhistory',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='supplierorderitem',
            name='total',
        ),
        migrations.RemoveField(
            model_name='suppliersynclog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='apihealthcheck',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время проверки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apihealthcheck',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='apihealthcheck',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='API доступен'),
        ),
        migrations.AddField(
            model_name='apihealthcheck',
            name='response_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Время ответа (сек)'),
        ),
        migrations.AddField(
            model_name='apihealthcheck',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='HTTP статус'),
        ),
        migrations.AddField(
            model_name='apimonitorlog',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время проверки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierbalancetransaction',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='supplierclientgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='supplierorderhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderstatus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='article',
            field=models.CharField(db_index=True, default=1, max_length=64, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='availability',
            field=models.IntegerField(default=0, verbose_name='Доступно'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='brand',
            field=models.CharField(db_index=True, default=1, max_length=64, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliersynclog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='suppliersynclog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apihealthcheck',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_health_checks', to='catalog.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='apimonitorlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='apimonitorlog',
            name='method',
            field=models.CharField(max_length=64, verbose_name='Метод API'),
        ),
        migrations.AlterField(
            model_name='apimonitorlog',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные запроса'),
        ),
        migrations.AlterField(
            model_name='apimonitorlog',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные ответа'),
        ),
        migrations.AlterField(
            model_name='apimonitorlog',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='apimonitorlog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_monitor_logs', to='catalog.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplierbalancetransaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='catalog.supplierclient', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='supplierbalancetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='supplierbalancetransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='catalog.supplierorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='supplierbalancetransaction',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='catalog.supplierstaff', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='supplierbalancetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Пополнение'), ('out', 'Списание')], max_length=32, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные клиента'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='catalog.supplierclientgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='catalog.supplierstaff', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='supplierclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='supplierclientgroup',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные группы'),
        ),
        migrations.AlterField(
            model_name='supplierclientgroup',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='supplierclientgroup',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='supplierdeliverymethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='supplierdeliverymethod',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные способа доставки'),
        ),
        migrations.AlterField(
            model_name='supplierdeliverymethod',
            name='days_max',
            field=models.PositiveIntegerField(default=7, verbose_name='Макс. дней'),
        ),
        migrations.AlterField(
            model_name='supplierdeliverymethod',
            name='days_min',
            field=models.PositiveIntegerField(default=1, verbose_name='Мин. дней'),
        ),
        migrations.AlterField(
            model_name='supplierdeliverymethod',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='supplierdeliverymethod',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supplierdeliverymethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.supplierclient', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные заказа'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.supplierdeliverymethod', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.supplierorderstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='article',
            field=models.CharField(blank=True, max_length=64, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='brand',
            field=models.CharField(blank=True, max_length=64, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные позиции'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='supplierorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.supplierproduct', verbose_name='Товар поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierorderstatus',
            name='color',
            field=models.CharField(default='#6c757d', max_length=16, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='supplierorderstatus',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные статуса'),
        ),
        migrations.AlterField(
            model_name='supplierorderstatus',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='supplierorderstatus',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='supplierstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='supplierstaff',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные сотрудника'),
        ),
        migrations.AlterField(
            model_name='supplierstaff',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='supplierstaff',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='supplierstaff',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='supplierstaff',
            name='role',
            field=models.CharField(blank=True, max_length=64, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='supplierstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='suppliersynclog',
            name='errors_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='suppliersynclog',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение/лог'),
        ),
        migrations.AlterField(
            model_name='suppliersynclog',
            name='products_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Создано товаров'),
        ),
        migrations.AlterField(
            model_name='suppliersynclog',
            name='products_updated',
            field=models.PositiveIntegerField(default=0, verbose_name='Обновлено товаров'),
        ),
        migrations.AlterField(
            model_name='suppliersynclog',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('in_progress', 'В процессе')], default='in_progress', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='supplierproduct',
            index=models.Index(fields=['article', 'brand'], name='catalog_sup_article_661e6e_idx'),
        ),
        migrations.RemoveField(
            model_name='supplierclientgroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierclientgroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplierorderstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierorderstatus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='data',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier_article',
        ),
    ]
