# Generated by Django 5.2.4 on 2025-07-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_apihealthcheck_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_supplier',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='api_secret',
        ),
        migrations.AddField(
            model_name='supplier',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='API токен'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='admin_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Admin логин'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='admin_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Admin пароль'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин API'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль API'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_shipment_address',
            field=models.CharField(default='0', max_length=10, verbose_name='Адрес доставки по умолчанию'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='office_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID офиса'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='use_mock_admin_api',
            field=models.BooleanField(default=True, verbose_name='Использовать mock admin API'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='use_online_stocks',
            field=models.BooleanField(default=True, verbose_name='Использовать онлайн остатки'),
        ),
    ]
