# Generated by Django 5.2.4 on 2025-07-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_product_primary_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='use_mock_admin_api',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупочная цена'),
        ),
    ]
