# Generated by Django 5.2.4 on 2025-07-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_supplier_use_mock_admin_api_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OemNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='OEM номер')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'OEM номер',
                'verbose_name_plural': 'OEM номера',
                'ordering': ['manufacturer', 'number'],
                'unique_together': {('number', 'manufacturer')},
            },
        ),
        migrations.CreateModel(
            name='ProductOem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной номер')),
                ('oem_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.oemnumber', verbose_name='OEM номер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oem_numbers', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'OEM номер товара',
                'verbose_name_plural': 'OEM номера товаров',
                'unique_together': {('product', 'oem_number')},
            },
        ),
    ]
