# Generated by Django 5.2.4 on 2025-07-09 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_oemnumber_productoem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('query', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('found_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('order_data', models.JSONField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'brand'], name='catalog_ord_article_0d59a1_idx'), models.Index(fields=['created_at'], name='catalog_ord_created_1f0708_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('item_key', models.CharField(max_length=100)),
                ('supplier_code', models.CharField(max_length=100)),
                ('original_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'supplier', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('query_type', models.CharField(max_length=50)),
                ('query_params', models.JSONField()),
                ('result_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key'], name='catalog_sea_cache_k_782ced_idx'), models.Index(fields=['expires_at'], name='catalog_sea_expires_a461ff_idx'), models.Index(fields=['query_type', 'supplier'], name='catalog_sea_query_t_07a9af_idx')],
            },
        ),
    ]
