# Generated by Django 5.2.4 on 2025-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_searchhistory_orderedproduct_savedproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Срок поставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100, verbose_name='Склад'),
        ),
    ]
