# Generated by Django 5.0 on 2025-07-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_delivery_time_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_spb_north', models.BooleanField(default=True, verbose_name='СПб Север')),
                ('show_spb_south', models.BooleanField(default=True, verbose_name='СПб Юг')),
                ('show_moscow', models.BooleanField(default=True, verbose_name='Москва')),
                ('show_other', models.BooleanField(default=True, verbose_name='Все другие')),
            ],
            options={
                'verbose_name': 'Настройки складов',
                'verbose_name_plural': 'Настройки складов',
            },
        ),
    ]
