# Generated by Django 5.0 on 2025-07-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_warehousesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=64, verbose_name='Срок поставки'),
        ),
    ]
