# Generated by Django 5.0 on 2025-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_supplierproduct_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='country_iso',
            field=models.CharField(blank=True, max_length=2, verbose_name='ISO-код страны (например, pl, de, cn)'),
        ),
    ]
