# Generated by Django 5.0 on 2025-07-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_brand_country_iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='online_catalog',
            field=models.URLField(blank=True, verbose_name='Онлайн каталог'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='show_moscow',
            field=models.BooleanField(default=True, verbose_name='Москва'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='show_other',
            field=models.BooleanField(default=True, verbose_name='Все остальные'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='show_spb_north',
            field=models.BooleanField(default=True, verbose_name='СПб Север'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='show_spb_south',
            field=models.BooleanField(default=True, verbose_name='СПб Юг'),
        ),
        migrations.AddField(
            model_name='warehousesettings',
            name='show_avtosp',
            field=models.BooleanField(default=True, verbose_name='Авто-Сп'),
        ),
    ]
