# Generated by Django 5.0 on 2025-07-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_brand_online_catalog_supplier_show_moscow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5★ Премиум'), (4, '4★ Хорошее'), (3, '3★ Средний'), (2, '2★ Низкий'), (1, '1★ Плохой')], null=True, verbose_name='Рейтинг бренда'),
        ),
    ]
