# Generated by Django 5.0 on 2025-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_brand_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoKontinentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('article', models.CharField(max_length=100, verbose_name='Код товара')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('stock_spb', models.PositiveIntegerField(default=0, verbose_name='Кол-во СПб')),
                ('stock_msk', models.PositiveIntegerField(default=0, verbose_name='Кол-во МСК')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('multiplicity', models.PositiveIntegerField(default=1, verbose_name='Кратность')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. изм.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар АвтоКонтинента',
                'verbose_name_plural': 'Товары АвтоКонтинента',
                'indexes': [models.Index(fields=['article'], name='catalog_aut_article_c2c29d_idx'), models.Index(fields=['brand'], name='catalog_aut_brand_9baa07_idx')],
                'unique_together': {('brand', 'article')},
            },
        ),
    ]
