# Generated by Django 5.0 on 2025-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_autokontinentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='autokontinentproduct',
            name='stock_spb_north',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во СЕВ_СПб'),
        ),
    ]
