# Generated by Django 5.0 on 2025-07-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_autokontinentproduct_stock_spb_north'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='autokontinentproduct',
            index=models.Index(fields=['article', 'brand'], name='catalog_aut_article_974595_idx'),
        ),
        migrations.AddIndex(
            model_name='autokontinentproduct',
            index=models.Index(fields=['updated_at'], name='catalog_aut_updated_a83c86_idx'),
        ),
        migrations.AddIndex(
            model_name='autokontinentproduct',
            index=models.Index(fields=['stock_spb_north'], name='catalog_aut_stock_s_0341eb_idx'),
        ),
        migrations.AddIndex(
            model_name='autokontinentproduct',
            index=models.Index(fields=['stock_spb'], name='catalog_aut_stock_s_cfcf96_idx'),
        ),
        migrations.AddIndex(
            model_name='autokontinentproduct',
            index=models.Index(fields=['stock_msk'], name='catalog_aut_stock_m_da6f5a_idx'),
        ),
    ]
