# Generated by Django 5.0 on 2025-07-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_autokontinentproduct_catalog_aut_article_974595_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikadoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_number', models.CharField(max_length=100, verbose_name='Номер производителя')),
                ('code', models.CharField(max_length=100, verbose_name='Внутренний код')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('multiplicity', models.PositiveIntegerField(default=1, verbose_name='Кратность поставки')),
                ('commentary', models.TextField(blank=True, verbose_name='Комментарий')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар Mikado',
                'verbose_name_plural': 'Товары Mikado',
                'indexes': [models.Index(fields=['article'], name='catalog_mik_article_8b84cd_idx'), models.Index(fields=['brand'], name='catalog_mik_brand_eab6fa_idx'), models.Index(fields=['code'], name='catalog_mik_code_256065_idx'), models.Index(fields=['producer_number'], name='catalog_mik_produce_edf86d_idx'), models.Index(fields=['article', 'brand'], name='catalog_mik_article_498014_idx'), models.Index(fields=['updated_at'], name='catalog_mik_updated_1eacbf_idx'), models.Index(fields=['stock_quantity'], name='catalog_mik_stock_q_e35f08_idx')],
                'unique_together': {('brand', 'article')},
            },
        ),
    ]
