# Generated by Django 5.0 on 2025-07-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_mikadoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikadoproduct',
            name='warehouse',
            field=models.CharField(default='ЦС-МК', max_length=50, verbose_name='Склад'),
        ),
    ]
