# Generated by Django 5.0 on 2025-07-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_mikadoproduct_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikadoproduct',
            name='warehouse',
            field=models.CharField(default='ЦС-МК', max_length=100, verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='MikadosProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_number', models.CharField(max_length=100, verbose_name='Номер производителя')),
                ('code', models.CharField(max_length=100, verbose_name='Внутренний код')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('multiplicity', models.PositiveIntegerField(default=1, verbose_name='Кратность поставки')),
                ('commentary', models.TextField(blank=True, verbose_name='Комментарий')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.')),
                ('warehouse', models.CharField(default='ЦС-МК', max_length=50, verbose_name='Склад')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар Микадоса',
                'verbose_name_plural': 'Товары Микадоса',
                'indexes': [models.Index(fields=['article'], name='catalog_mik_article_a0199f_idx'), models.Index(fields=['brand'], name='catalog_mik_brand_4a77e7_idx'), models.Index(fields=['code'], name='catalog_mik_code_68250a_idx'), models.Index(fields=['producer_number'], name='catalog_mik_produce_a207f7_idx'), models.Index(fields=['article', 'brand'], name='catalog_mik_article_e86ecf_idx'), models.Index(fields=['updated_at'], name='catalog_mik_updated_cda45c_idx'), models.Index(fields=['stock_quantity'], name='catalog_mik_stock_q_a9ac83_idx')],
                'unique_together': {('brand', 'article')},
            },
        ),
    ]
