# Generated by Django 5.0 on 2025-07-31 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_mikadoproduct_warehouse_mikadosproduct'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mikadosproduct',
            name='catalog_mik_produce_a207f7_idx',
        ),
        migrations.RemoveField(
            model_name='mikadosproduct',
            name='producer_number',
        ),
    ]
