# Generated by Django 5.0 on 2025-07-26 07:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='old_status',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='new_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('confirmed', 'Подтверждён'), ('in_progress', 'В работе'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('returned', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказах'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Компания доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('post', 'Почта России'), ('transport', 'Транспортная компания')], default='pickup', max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма без скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итоговая сумма'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий пользователя'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='article',
            field=models.CharField(default='', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к товару'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(default='В обработке', max_length=50, verbose_name='Статус товара'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='manufacturer',
            field=models.CharField(default='', max_length=100, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Банковской картой'), ('bank_transfer', 'Банковский перевод'), ('online', 'Онлайн оплата')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='orders/documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Документ заказа',
                'verbose_name_plural': 'Документы заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=20, verbose_name='Статус с')),
                ('status_to', models.CharField(max_length=20, verbose_name='Статус на')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
    ]
